// SA Bursary & Scholarship database — curated for VarsityOS
// Fields kept intentionally broad (no real deadlines hardcoded as they change yearly)

export type BursaryType = 'bursary' | 'scholarship' | 'loan-bursary'
export type BursaryBasis = 'need' | 'merit' | 'both'

export interface Bursary {
  id:          string
  name:        string
  provider:    string
  type:        BursaryType
  basis:       BursaryBasis
  amount:      string          // human-readable e.g. "R60 000/year"
  fields:      string[]        // fields of study covered
  years:       string          // eligible year of study e.g. "1st–4th year"
  description: string
  requirements: string[]
  howToApply:  string
  contact:     string
  deadline:    string          // "Usually opens April" etc.
  tag:         string          // short highlight tag shown on card
}

export const BURSARIES: Bursary[] = [
  {
    id: 'funza-lushaka',
    name: 'Funza Lushaka Bursary',
    provider: 'Department of Basic Education',
    type: 'bursary',
    basis: 'both',
    amount: 'Full cost of study (tuition + accommodation + books)',
    fields: ['Education', 'Teaching'],
    years: '1st–4th year (B.Ed or PGCE)',
    description: 'Fully funded bursary for students wanting to become teachers at public schools. In exchange you teach at a public school for as many years as funded.',
    requirements: [
      'Enrolled in a B.Ed or PGCE at a public university',
      'South African citizen',
      'Commit to teaching at a public school after graduation',
      'Teaching subjects in shortage: Maths, Science, Technology, Accounting',
    ],
    howToApply: 'Apply via the Funza Lushaka website or your university financial aid office. Applications usually open in April.',
    contact: 'funzalushaka.doe.gov.za',
    deadline: 'Usually opens April — check funzalushaka.doe.gov.za each year',
    tag: '🏫 Full cost + Teaching career',
  },
  {
    id: 'sasol-inzalo',
    name: 'Sasol Inzalo Foundation Bursary',
    provider: 'Sasol Inzalo Foundation',
    type: 'bursary',
    basis: 'both',
    amount: 'Full tuition + accommodation + books + stipend',
    fields: ['Engineering', 'Science', 'Mathematics', 'Technology'],
    years: '1st year (apply before first year)',
    description: 'One of SA\'s most prestigious STEM bursaries. Covers full study costs plus living allowance. Includes vacation work and a possible full-time job offer after graduation.',
    requirements: [
      'South African citizen',
      'Matric with 70%+ Maths and Physical Science',
      'Enrolled or planning to enrol in an accredited engineering/science degree',
      'Preference for students from disadvantaged backgrounds',
    ],
    howToApply: 'Apply via the Sasol Inzalo Foundation website. Applications open in March/April for first-year students.',
    contact: 'inzalo.sasol.com',
    deadline: 'Applications typically open March — closes May',
    tag: '⚗️ STEM · Full + stipend',
  },
  {
    id: 'old-mutual',
    name: 'Old Mutual Bursary',
    provider: 'Old Mutual Foundation',
    type: 'bursary',
    basis: 'both',
    amount: 'Up to R60 000/year',
    fields: ['Commerce', 'Finance', 'Accounting', 'Actuarial Science', 'IT', 'Engineering'],
    years: '2nd year and above (with good academic record)',
    description: 'Old Mutual awards bursaries to academically strong students in commerce, finance, and related fields. Often leads to internship/job opportunities at Old Mutual.',
    requirements: [
      'South African citizen',
      '60%+ academic average',
      'Financial need',
      'Studying a qualifying field',
    ],
    howToApply: 'Visit the Old Mutual Foundation website or contact your university financial aid office.',
    contact: 'oldmutualfoundation.co.za',
    deadline: 'Usually opens August–September for next academic year',
    tag: '💼 Commerce & Finance',
  },
  {
    id: 'eskom',
    name: 'Eskom Bursary',
    provider: 'Eskom',
    type: 'bursary',
    basis: 'merit',
    amount: 'Full tuition + accommodation + books + R4 000 monthly stipend',
    fields: ['Engineering', 'Science', 'Finance', 'IT', 'Human Resources'],
    years: '1st–4th year',
    description: 'Eskom funds high-achieving students in technical and business fields with the expectation of working for Eskom after graduation.',
    requirements: [
      'South African citizen',
      '70%+ Maths and Science in matric (engineering)',
      '65%+ overall academic average',
      'Willing to work for Eskom post-graduation',
    ],
    howToApply: 'Apply at eskom.co.za/Pages/bursaries. Applications open annually, usually in March.',
    contact: 'eskom.co.za/bursaries',
    deadline: 'March–May each year',
    tag: '⚡ Engineering · Full + R4k/month',
  },
  {
    id: 'transnet',
    name: 'Transnet Bursary',
    provider: 'Transnet SOC Ltd',
    type: 'bursary',
    basis: 'merit',
    amount: 'Full tuition + accommodation + books',
    fields: ['Engineering', 'Logistics', 'Finance', 'IT', 'Supply Chain'],
    years: '1st–4th year',
    description: 'Transnet supports students studying in fields relevant to transport, logistics, and infrastructure development.',
    requirements: [
      'South African citizen',
      'Strong Maths/Science results for engineering',
      'Good overall academic performance',
      'Internship obligation at Transnet',
    ],
    howToApply: 'Visit transnet.net and search for bursaries. Applications open early each year.',
    contact: 'transnet.net/bursaries',
    deadline: 'Typically January–March',
    tag: '🚂 Logistics & Engineering',
  },
  {
    id: 'mtn-foundation',
    name: 'MTN SA Foundation Bursary',
    provider: 'MTN SA Foundation',
    type: 'bursary',
    basis: 'need',
    amount: 'Tuition + accommodation + books',
    fields: ['ICT', 'Engineering', 'Science', 'Mathematics'],
    years: '1st year+',
    description: 'MTN Foundation supports students from disadvantaged backgrounds studying in ICT and STEM fields, aligned with South Africa\'s digital future.',
    requirements: [
      'South African citizen from a disadvantaged background',
      'Good Maths and Science results',
      'Enrolled in a qualifying ICT/STEM degree',
    ],
    howToApply: 'Apply via the MTN Foundation website or through select university financial aid offices.',
    contact: 'mtn.co.za/foundation',
    deadline: 'Usually September–October for the following year',
    tag: '📱 ICT & STEM · Need-based',
  },
  {
    id: 'absa',
    name: 'Absa Bank Bursary',
    provider: 'Absa Group',
    type: 'bursary',
    basis: 'both',
    amount: 'Up to R65 000/year',
    fields: ['Commerce', 'Finance', 'Accounting', 'IT', 'Engineering'],
    years: '2nd year and above',
    description: 'Absa offers bursaries to high-performing students, often paired with an internship at Absa during academic vacations.',
    requirements: [
      'South African citizen',
      '65%+ academic average',
      'Financial need',
      'Second-year student or above',
    ],
    howToApply: 'Apply via absa.co.za/bursaries or through your university financial aid office.',
    contact: 'absa.co.za/bursaries',
    deadline: 'Applications typically open July–September',
    tag: '🏦 Banking · Internship included',
  },
  {
    id: 'standard-bank',
    name: 'Standard Bank Bursary',
    provider: 'Standard Bank Group',
    type: 'bursary',
    basis: 'merit',
    amount: 'Full tuition + living allowance',
    fields: ['Finance', 'Accounting', 'Commerce', 'IT', 'Engineering', 'Actuarial Science'],
    years: '2nd–final year',
    description: 'Standard Bank supports strong academic performers in finance and technical disciplines, with potential employment opportunities after completion.',
    requirements: [
      'South African citizen',
      '70%+ academic average',
      'Second year and above',
    ],
    howToApply: 'Apply online at standardbank.co.za or via your university financial aid office.',
    contact: 'standardbank.co.za/bursaries',
    deadline: 'Applications open around August each year',
    tag: '🏦 Banking · Merit-based',
  },
  {
    id: 'nedbank',
    name: 'Nedbank Bursary',
    provider: 'Nedbank Group',
    type: 'bursary',
    basis: 'both',
    amount: 'Tuition + accommodation + books + stipend',
    fields: ['Finance', 'Accounting', 'Commerce', 'IT', 'Data Science'],
    years: '1st year+',
    description: 'Nedbank funds students in banking-relevant fields and offers vacation work placements.',
    requirements: [
      'South African citizen',
      '60%+ academic average',
      'Financial need considered',
    ],
    howToApply: 'Apply via nedbank.co.za/bursaries.',
    contact: 'nedbank.co.za/bursaries',
    deadline: 'Usually opens September–October',
    tag: '🌿 Banking & Finance',
  },
  {
    id: 'fnb',
    name: 'FNB Bursary (RMB/FirstRand Group)',
    provider: 'FirstRand Group',
    type: 'bursary',
    basis: 'merit',
    amount: 'Tuition + accommodation + books',
    fields: ['Finance', 'Actuarial Science', 'Commerce', 'Engineering', 'Data Science', 'IT'],
    years: '1st–final year',
    description: 'FirstRand Group (which includes FNB, RMB, and Wesbank) funds exceptional students with potential for permanent placement.',
    requirements: [
      'South African citizen',
      '70%+ in Maths (for quantitative fields)',
      'Strong overall academic performance',
    ],
    howToApply: 'Via fnb.co.za or firstrand.co.za career pages.',
    contact: 'firstrand.co.za/bursaries',
    deadline: 'Usually September–November each year',
    tag: '💳 Finance · Quant focus',
  },
  {
    id: 'telkom-foundation',
    name: 'Telkom Foundation Bursary',
    provider: 'Telkom Foundation',
    type: 'bursary',
    basis: 'both',
    amount: 'Tuition + accommodation + books',
    fields: ['ICT', 'Engineering', 'Science', 'Mathematics', 'Commerce'],
    years: '1st year+',
    description: 'Telkom Foundation supports students in ICT and STEM fields, aiming to develop SA\'s digital talent pipeline.',
    requirements: [
      'South African citizen',
      'Disadvantaged background preferred',
      'Studying a qualifying field at a public university',
    ],
    howToApply: 'Visit telkom.co.za/foundation or your university financial aid office.',
    contact: 'telkom.co.za/foundation',
    deadline: 'Applications open October–November',
    tag: '📡 ICT · Disadvantaged preference',
  },
  {
    id: 'department-health-bursary',
    name: 'National Department of Health Bursary',
    provider: 'National Department of Health',
    type: 'bursary',
    basis: 'need',
    amount: 'Full cost of study + living allowance',
    fields: ['Medicine', 'Nursing', 'Pharmacy', 'Dentistry', 'Allied Health'],
    years: '1st year+',
    description: 'The Department of Health funds students in healthcare fields in exchange for compulsory community service in underserved areas post-graduation.',
    requirements: [
      'South African citizen',
      'Enrolled in a health sciences degree at a public university',
      'Commit to work in the public health sector post-graduation',
      'Financial need',
    ],
    howToApply: 'Apply through your provincial Department of Health or health.gov.za.',
    contact: 'health.gov.za',
    deadline: 'Applications open February–April each year',
    tag: '🏥 Healthcare · Full cost',
  },
  {
    id: 'agricultural-research',
    name: 'Agricultural Research Council Bursary',
    provider: 'Agricultural Research Council (ARC)',
    type: 'bursary',
    basis: 'merit',
    amount: 'Tuition + living allowance',
    fields: ['Agriculture', 'Food Science', 'Veterinary Science', 'Environmental Science'],
    years: 'Undergraduate & postgraduate',
    description: 'ARC supports students in agricultural sciences to address SA\'s food security challenges.',
    requirements: [
      'South African citizen',
      'Enrolled in an agricultural or related sciences degree',
      'Good academic standing',
    ],
    howToApply: 'Visit arc.agric.za or contact ARC directly.',
    contact: 'arc.agric.za',
    deadline: 'Check arc.agric.za — applications open throughout the year',
    tag: '🌱 Agriculture & Food',
  },
  {
    id: 'anglo-american',
    name: 'Anglo American Zimele Bursary',
    provider: 'Anglo American',
    type: 'bursary',
    basis: 'both',
    amount: 'Tuition + accommodation + books + stipend',
    fields: ['Engineering', 'Mining', 'Science', 'Finance', 'IT'],
    years: '1st–4th year',
    description: 'Anglo American funds students in mining, engineering, and business disciplines with a focus on transformation and diversity in the mining sector.',
    requirements: [
      'South African citizen',
      'Good Maths/Science results',
      'Interest in the mining or resources sector',
      'Financial need',
    ],
    howToApply: 'Via angloamerican.com/careers or zimele.co.za.',
    contact: 'angloamerican.com/bursaries',
    deadline: 'Applications usually open March–May',
    tag: '⛏️ Mining & Engineering',
  },
  {
    id: 'idc-bursary',
    name: 'IDC Bursary (Industrial Development Corporation)',
    provider: 'Industrial Development Corporation',
    type: 'bursary',
    basis: 'both',
    amount: 'Tuition + accommodation + living allowance',
    fields: ['Engineering', 'Finance', 'Economics', 'Commerce', 'Science'],
    years: '1st–final year',
    description: 'The IDC develops industrial capacity in SA and supports students studying in development-relevant fields.',
    requirements: [
      'South African citizen',
      'Good academic record',
      'Financial need considered',
    ],
    howToApply: 'Apply at idc.co.za.',
    contact: 'idc.co.za',
    deadline: 'Applications open September each year',
    tag: '🏭 Industrial development',
  },
  {
    id: 'sappi-bursary',
    name: 'Sappi Bursary',
    provider: 'Sappi Southern Africa',
    type: 'bursary',
    basis: 'merit',
    amount: 'Full tuition + accommodation + books',
    fields: ['Engineering', 'Chemistry', 'Chemical Engineering', 'Forestry', 'Finance'],
    years: '1st year+',
    description: 'Sappi, a global pulp and paper company, funds students in technical disciplines. Includes vacation work opportunities.',
    requirements: [
      'South African citizen',
      'Strong Maths/Science matric results',
      'Enrolled in a qualifying technical or business degree',
    ],
    howToApply: 'Apply via sappi.com/southern-africa or through select universities.',
    contact: 'sappi.com/bursaries',
    deadline: 'Applications open in September each year',
    tag: '🌳 Paper/Chemicals · Engineering',
  },
  {
    id: 'dhet-nsfas',
    name: 'NSFAS (National Student Financial Aid Scheme)',
    provider: 'Department of Higher Education',
    type: 'loan-bursary',
    basis: 'need',
    amount: 'Full tuition + accommodation up to R45 625/year + meal + books allowances',
    fields: ['All fields at public universities and TVET colleges'],
    years: 'All years (N+ Rule applies)',
    description: 'NSFAS is the primary government financial aid scheme for students from households earning under R350 000/year. Covers tuition, accommodation, meals, books, and transport. Can convert to bursary if conditions met.',
    requirements: [
      'South African citizen',
      'Household income ≤ R350 000/year (combined)',
      'Enrolled at a public university or TVET college',
      'Not exceeding N+ (degree duration + 2 extra years)',
      'Minimum pass rate: 50% of enrolled modules per year',
    ],
    howToApply: 'Apply via my.nsfas.org.za before 30 November each year. Use your myNSFAS portal for status and queries.',
    contact: 'my.nsfas.org.za | 0800 067 327 (toll-free)',
    deadline: 'Applications open September — close 30 November',
    tag: '🇿🇦 Government · Need-based · All fields',
  },
  {
    id: 'deloitte-bursary',
    name: 'Deloitte Bursary',
    provider: 'Deloitte Africa',
    type: 'bursary',
    basis: 'merit',
    amount: 'Tuition + accommodation + books',
    fields: ['Accounting', 'Finance', 'Actuarial Science', 'Commerce', 'IT', 'Data Analytics'],
    years: '2nd–final year',
    description: 'Deloitte awards bursaries to high-performing students in commerce and analytical fields, often converting to job offers at Deloitte after graduation.',
    requirements: [
      'South African citizen',
      '70%+ academic average',
      'Studying a qualifying degree',
      'Second year or above',
    ],
    howToApply: 'Via deloitte.com/za/bursaries or LinkedIn.',
    contact: 'deloitte.com/za',
    deadline: 'Applications usually open August–September',
    tag: '💡 Consulting · Accounting',
  },
  {
    id: 'pwc-bursary',
    name: 'PwC Bursary',
    provider: 'PricewaterhouseCoopers SA',
    type: 'bursary',
    basis: 'merit',
    amount: 'Tuition + accommodation + books',
    fields: ['Accounting', 'Auditing', 'Finance', 'Actuarial Science', 'Tax'],
    years: '1st–final year (CA track)',
    description: 'PwC offers bursaries to future chartered accountants and finance professionals with a clear pathway to articles and employment.',
    requirements: [
      'South African citizen',
      '70%+ in accounting/maths',
      'Clear interest in pursuing CA(SA) or similar qualification',
    ],
    howToApply: 'Via pwc.com/za/careers or directly through CA campus programmes.',
    contact: 'pwc.com/za',
    deadline: 'Applications open February–March for academic year',
    tag: '📊 CA · Accounting · Big 4',
  },
  {
    id: 'ey-bursary',
    name: 'EY (Ernst & Young) Bursary',
    provider: 'Ernst & Young Africa',
    type: 'bursary',
    basis: 'merit',
    amount: 'Tuition + accommodation',
    fields: ['Accounting', 'Finance', 'Tax', 'Auditing', 'Actuarial Science'],
    years: '1st–final year',
    description: 'EY supports future CA(SA) candidates and finance professionals with bursaries and internship opportunities.',
    requirements: [
      'South African citizen',
      '65%+ academic average',
      'Enrolled in a qualifying commerce/accounting degree',
    ],
    howToApply: 'Via ey.com/za/careers.',
    contact: 'ey.com/za',
    deadline: 'Applications open July–September',
    tag: '📊 CA · Audit · Big 4',
  },
  {
    id: 'google-generation-scholarship',
    name: 'Generation Google Scholarship',
    provider: 'Google',
    type: 'scholarship',
    basis: 'merit',
    amount: 'USD 10 000 (~R185 000)',
    fields: ['Computer Science', 'Software Engineering', 'IT', 'Data Science', 'AI'],
    years: '2nd year and above (undergrad or postgrad)',
    description: 'Google awards annual scholarships to women and underrepresented groups in tech across Sub-Saharan Africa. Includes mentoring and Google Summer Institute events.',
    requirements: [
      'Enrolled at a university in Sub-Saharan Africa',
      'Studying CS, Software Engineering, or related',
      '3.2+ GPA or equivalent',
      'Women or underrepresented minorities in tech preferred',
    ],
    howToApply: 'Apply at buildyourfuture.withgoogle.com/scholarships.',
    contact: 'buildyourfuture.withgoogle.com',
    deadline: 'Usually opens October — closes November',
    tag: '🌐 Tech · International · Women/URG',
  },
]

// ── Filter helpers ─────────────────────────────────────────────────────────────

export const ALL_FIELDS = Array.from(
  new Set(BURSARIES.flatMap(b => b.fields))
).sort()

export type BursaryBasisFilter = 'all' | 'need' | 'merit' | 'both'

export function filterBursaries(
  bursaries: Bursary[],
  query:  string,
  field:  string,
  basis:  BursaryBasisFilter,
): Bursary[] {
  const q = query.toLowerCase().trim()
  return bursaries.filter(b => {
    if (q && !b.name.toLowerCase().includes(q) && !b.provider.toLowerCase().includes(q) && !b.description.toLowerCase().includes(q) && !b.fields.some(f => f.toLowerCase().includes(q))) return false
    if (field && !b.fields.some(f => f.toLowerCase().includes(field.toLowerCase()))) return false
    if (basis !== 'all' && b.basis !== basis && !(basis === 'both')) return false
    return true
  })
}
